server:
  port: 8006
spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    consul:
      host: 192.168.197.129
      port: 8500
      discovery:
        hostname: ${spring.application.name}
mybatis:
  type-aliases-package: com.shengsheng.com.shengsheng.springcloud.entities
  mapper-locations: classpath:mapper/*.xml